language: python
python:
- 3.8
- 3.7
install: pip install -U tox-travis
script: tox
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: qwedfgr
  password:
    secure: m/YvHPlBgQ5wpGIdNAk1s9D+viy5ktNrNJ9zSYSp7hUrfKvwudDRvrwW0rxV288qXErZUVuzsIlfnpWw2OuTGCy2luWTk5vZeRLFukEhTCHKojFZK9FDitAu4YiRM8ozIlXtCKK5xfOOOqMDEnYJ2oVUVg3lcZrSAXSzZCPFaW0z9rzw3OC+3Ep60MB5SStI055EkbNw7u0fhJ1lJ2tWwFfqh4welf56Eyijo/Mhxh2dTejjXvMva6MYjecINtghXzFBRm0ljtaS40qgd3Qg5kcsnPxzeSan/hhW5VTjr64ps+NBaGaRxkAVOCN8V4zZSFsTNfu6iSU+Czx+aWN94RSdmGgvbauZdzaDZsWgGpopgRc97fAxVuOzIQkSXrbPeuf8BZkN0/iYx5inzdHC6W/YB2j7kn7jEF5l6lm35GbSVrAAkAIADmeEhZEr3nvaC3CMRa6NPeO7uUgBd96LoLqyTzLGmeXYhYsJ/NkMbW5jyMplH0uy5Mg1MJpyMqf2bL9o2KJxrTyepFqTb6CoOywsEXvDDX/Qp+Qywm+/2LBH6d9srp7AL+e0wcoO0iLlBDvaa3Pq+/1cHvS+4HbKotePxIfBe/knH8IGpSwyhbCVKSjC0msZvWQobSvwBwuSGIoaRdfXEFQdNIC6Ca1nXfesZEXrcXpzdYRwh00E5Vk=
  on:
    tags: true
    repo: Qwedfgr/tools_1c
    python: 3.7
