variables:
  CLUSTERS:
    DEV:1641:
      host: 'dev'
      port: 1641
      ras_port: 1645
      version: '8.3.14.1854'
    DEV:
      host: 'dev'
      port: 1541
      ras_port: 1545
      version: '8.3.13.1809'
    DEV:1741:
      host: 'dev'
      port: 1741
      ras_port: 1745
      version: '8.3.15.1747'
  SQL_SERVERS:
    DEV:
      DBMS: 'MSSQLServer'
      DB_HOST: 'dev'
      DB_USER: 'DB_USER'
      DB_PASSWORD: 'DB_PASSWORD'
